### ISSUE TITLE
[EXECUTE-ANSIBLE-PLAYBOOKS][FEATURE] - ADD ABILITY FOR GIVING COMPLEX VARS AS B64

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stage-time#3]
HOW DO WE WANT TO USE THIS FEATURE:

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
  labels:
    tekton.dev/pipeline: execute-ansible-playbooks
  name: monday5-9
  namespace: tekton-pipelines
spec:
  params:
  - name: extraVarsFile
    value: ghcr.io/stuttgart-things/sthings-ansible:11.0.0
#...
```

HOW CAN IT BE IMPLEMENTED:

DEFAULT IS EMPTY, IF SET DECODE FROM B64 AND MERGE WITH VARS FILE CREATED BY PARAMETERS.
