### ISSUE TITLE
[TEKTON PIPELINES][GIT-RESOLVER] - PIPELINE NOT RESOLVING FROM BRANCH/REVISION OTHER THAN MAIN

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stage-time#6]
## DOES WORK

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: execute-ansible-playbooks
  name: homerun-int-59qc4-2f520379562d-6
  namespace: tekton-pipelines
spec:
  pipelineRef:
    params:
    - name: url
      value: https://github.com/stuttgart-things/stage-time.git
    - name: revision
      value: main #pragma: allowlist secret
    - name: pathInRepo
      value: pipelines/execute-ansible-playbooks.yaml
    resolver: git
```

## SHOULD ALSO WORK (BUT DOES NOT)

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: execute-ansible-playbooks
  name: homerun-int-59qc4-2f520379562d-6
  namespace: tekton-pipelines
spec:
  pipelineRef:
    params:
    - name: url
      value: https://github.com/stuttgart-things/stage-time.git
    - name: revision
      value: feature/pipelines-update-ansible
    - name: pathInRepo
      value: pipelines/execute-ansible-playbooks.yaml
    resolver: git
```
